name: Build & Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    permissions: 
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        id: getversion
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Make build dir
        run: mkdir -p _build
      - name: Zip client mods
        run: zip -r _build/client_v${{ steps.getversion.outputs.version }}.zip BepInEx/plugins/
      - name: Zip server mods
        run: zip -r _build/server_v${{ steps.getversion.outputs.version }}.zip user/mods/
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "_build/*.zip"
          body: "MPT modpack release v${{ steps.getversion.outputs.version }}"
          tag: "v${{ steps.getversion.outputs.version }}"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Modpack update v${{ steps.getversion.outputs.version }} released & available to download [here](https://github.com/{{ EVENT_PAYLOAD.repository.full_name }}/releases/tag/v${{ steps.getversion.outputs.version }})!'
